Feature/news reader
alexandruoliva/News-Reader-Android-Advanced pull request #1
Opened 2021-06-26 08:30 UTC by alexandruoliva

2021-06-29 14:23 UTC, Misca requested changes
pretty close, good job

2021-06-29 14:23 UTC, Misca commented on app/src/main/java/com/oliva/newsreader/MainActivity.java
> +
let's rename this activity

2021-06-29 14:23 UTC, Misca commented on data/src/main/java/com/oliva/data/model/entities/local/ArticleEntity.java
> +    @PrimaryKey(autoGenerate = true)
let's: 
- remove all the setter and getters, as we don't want to encapsulate anything, the opposite (no logic and no inheritance)
- let's make all the filed final so that we get an immutable class (adding a constructor)

2021-07-07 07:50 UTC, alexandruoliva commented on data/src/main/java/com/oliva/data/model/entities/local/ArticleEntity.java
> +    @PrimaryKey(autoGenerate = true)
refactored

2021-07-07 07:50 UTC, alexandruoliva commented on app/src/main/java/com/oliva/newsreader/MainActivity.java
> +
refactored

2021-07-07 14:40 UTC, Misca approved these changes
GG 👍

2021-07-07 14:40 UTC, merged